// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/matchglee-landing/LandingPage.tsx": () => import("../components/mockups/matchglee-landing/LandingPage.tsx"),
  "./components/mockups/matchglee-variants/BoldChromatic.tsx": () => import("../components/mockups/matchglee-variants/BoldChromatic.tsx"),
  "./components/mockups/matchglee-variants/IridescentPearl.tsx": () => import("../components/mockups/matchglee-variants/IridescentPearl.tsx"),
  "./components/mockups/matchglee-variants/WarmEditorial.tsx": () => import("../components/mockups/matchglee-variants/WarmEditorial.tsx")
};
