// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/matchglee-concepts/CinematicStory.tsx": () => import("../components/mockups/matchglee-concepts/CinematicStory.tsx"),
  "./components/mockups/matchglee-concepts/CombinedExperience.tsx": () => import("../components/mockups/matchglee-concepts/CombinedExperience.tsx"),
  "./components/mockups/matchglee-concepts/DualScreen.tsx": () => import("../components/mockups/matchglee-concepts/DualScreen.tsx"),
  "./components/mockups/matchglee-concepts/InteractiveQuiz.tsx": () => import("../components/mockups/matchglee-concepts/InteractiveQuiz.tsx"),
  "./components/mockups/matchglee-concepts/PeopleFirst.tsx": () => import("../components/mockups/matchglee-concepts/PeopleFirst.tsx"),
  "./components/mockups/matchglee-landing/LandingPage.tsx": () => import("../components/mockups/matchglee-landing/LandingPage.tsx"),
  "./components/mockups/matchglee-surprises/AdaptiveChapters.tsx": () => import("../components/mockups/matchglee-surprises/AdaptiveChapters.tsx"),
  "./components/mockups/matchglee-surprises/ChapterMap.tsx": () => import("../components/mockups/matchglee-surprises/ChapterMap.tsx"),
  "./components/mockups/matchglee-surprises/InvertedArc.tsx": () => import("../components/mockups/matchglee-surprises/InvertedArc.tsx"),
  "./components/mockups/matchglee-variants/BoldChromatic.tsx": () => import("../components/mockups/matchglee-variants/BoldChromatic.tsx"),
  "./components/mockups/matchglee-variants/IridescentPearl.tsx": () => import("../components/mockups/matchglee-variants/IridescentPearl.tsx"),
  "./components/mockups/matchglee-variants/WarmEditorial.tsx": () => import("../components/mockups/matchglee-variants/WarmEditorial.tsx")
};
